### ISSUE TITLE
async not working

### ISSUE THREAD

**Issue by asadkhalili** [vuongxuongminh/yii2-async#2]
hi
I use async to run a function for send a event.
this my code: 
`
function myFunction(){
Yii::$app->async->run(function () {
                        $model = new Events();
                        $model->Call();
                    });
return 'ok';
}
`
i want to return 'ok'  when process Call(), for test i add 'sleep(5)' in Call() function, but return ok  after 5 seconds
sorry for english.

**Comment by vuongxuongminh** [comment]
It only work with pcntl extension enabled. What's your os?

**Comment by asadkhalili** [comment]
windows 8.1 and xampp v3.2.2
php 7.1

**Comment by vuongxuongminh** [comment]
On windows it's sync if you deploy server using unix so not care about that when you deploy on your server it will be async.
